### ISSUE TITLE
Lift error spam 1.8.3

### ISSUE THREAD

**Issue by xion87** [croxis/Lift#131]
Using Lift v52 and 1.83. spam this error
[17:06:11 WARN]: [Lift] Task #92 for Lift v52 generated an exception
java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftEntity.setVelocity(CraftEntity.java:205) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.croxis.plugins.lift.BukkitElevatorManager.endLift(BukkitElevatorManager.java:249) ~[?:?]
        at net.croxis.plugins.lift.BukkitElevatorManager.run(BukkitElevatorManager.java:404) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:720) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[17:06:11 WARN]: [Lift] Task #92 for Lift v52 generated an exception
java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_8_R2.entity.CraftEntity.setVelocity(CraftEntity.java:205) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.croxis.plugins.lift.BukkitElevatorManager.endLift(BukkitElevatorManager.java:249) ~[?:?]
        at net.croxis.plugins.lift.BukkitElevatorManager.run(BukkitElevatorManager.java:404) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-2ec6f06-7722428]
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:720) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-2ec6f06-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by croxis** [comment]
Should be fixed, I think?
