### ISSUE TITLE
Lift NPE

### ISSUE THREAD

**Issue by croxis** [croxis/Lift#143]
[16:23:44] [Server thread/WARN]: [Lift] Task #169458 for Lift v55 generated an exception
java.lang.NullPointerException
at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.setVelocity(CraftEntity.java:231) ~[patched_1.11.jar:git-Paper-968]
at net.croxis.plugins.lift.BukkitElevatorManager.endLift(BukkitElevatorManager.java:247) ~[?:?]
at net.croxis.plugins.lift.BukkitElevatorManager.run(BukkitElevatorManager.java:401) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.jar:git-Paper-968]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.11.jar:git-Paper-968]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:807) [patched_1.11.jar:git-Paper-968]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-968]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-968]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-968]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[16:23:45] [Server thread/WARN]: [Lift] Task #169458 for Lift v55 generated an exception
java.lang.NullPointerException
at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.setVelocity(CraftEntity.java:231) ~[patched_1.11.jar:git-Paper-968]
at net.croxis.plugins.lift.BukkitElevatorManager.endLift(BukkitElevatorManager.java:247) ~[?:?]
at net.croxis.plugins.lift.BukkitElevatorManager.run(BukkitElevatorManager.java:401) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.11.jar:git-Paper-968]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.11.jar:git-Paper-968]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:807) [patched_1.11.jar:git-Paper-968]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-968]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-968]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-968]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by david50407** [comment]
same here when I lifting minecart:

```
[00:31:16 WARN]: [Lift] Task #10 for Lift v${version} generated an exception
java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftEntity.setVelocity(CraftEntity.java:232) ~[server.jar:git-Spigot-283de8b-aa522c9]
        at net.croxis.plugins.lift.BukkitElevatorManager.endLift(BukkitElevatorManager.java:236) ~[?:?]
        at net.croxis.plugins.lift.BukkitElevatorManager.run(BukkitElevatorManager.java:393) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[server.jar:git-Spigot-283de8b-aa522c9]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [server.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [server.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [server.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-283de8b-aa522c9]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-283de8b-aa522c9]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
```
