### ISSUE TITLE
Lift sometimes breaks completely and spams the console

### ISSUE THREAD

**Issue by MicleBrick** [croxis/Lift#152]
[12:05:50] [Server thread/WARN]: [Lift] Task #79 for Lift v56 generated an exception
java.lang.IllegalArgumentException: velocity
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.12.2.jar:git-Paper-1428]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.setVelocity(CraftEntity.java:241) ~[patched_1.12.2.jar:git-Paper-1428]
	at net.croxis.plugins.lift.BukkitElevatorManager.endLift(BukkitElevatorManager.java:236) ~[Lift.jar:?]
	at net.croxis.plugins.lift.BukkitElevatorManager.run(BukkitElevatorManager.java:393) ~[Lift.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1428]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1428]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1428]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1428]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1428]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1428]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

**Comment by croxis** [comment]
I think this is when an entity dies or despawns mid lift, which I should now have code that takes care of. Reopen if it is still a problem in v59 or higher.
